### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by FredericaBernkastel** [imtbl/hyve#4]
**1.** It is unclear how to run multiple instances from a single source. This can be told for all 3 parts, server, sync and web.
I've changed `bin/www`, so it accepts environment file as an optional agrument:
```js
const envpath = '../' + (process.argv[2] ? process.argv[2] : '.env')
require('dotenv').config({ path: path.resolve(__dirname, envpath )})
```
Maybe there is a more idiomatic way?
Now systemd service can look like this:
<details>
  <summary>Spoiler</summary>

```
[Unit]
Description=hyve-dolls
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=bernkastel
ExecStart=/usr/bin/node /home/bernkastel/hyve/services/server/bin/www 'dolls.env'
WorkingDirectory=/home/bernkastel/hyve/services/server

[Install]
WantedBy=multi-user.target
```

</details>

**2.** Web needs a base path configuration, so it can be run in a subdirectory. In `vue.config.js` i've added:
```js
publicPath: process.env.VUE_APP_HYVE_BASE_URL
```
By default it should be `/`

**Comment by mserajnik** [comment]
Hey, thank you for this feedback.

Sorry, I won't find time before the weekend to properly look at this.
